config/routes.rb
Rails.application.routes.draw do
  
  # Routes for main resources
  resources :addresses
  resources :customers
  resources :orders
  resources :users
  resources :sessions
  resources :items
  resources :item_prices

  # Semi-static page routes
  get 'home' => 'home#home', as: :home
  get 'about' => 'home#about', as: :about
  get 'contact' => 'home#contact', as: :contact
  get 'privacy' => 'home#privacy', as: :privacy
  get 'login' => 'sessions#new', :as => :login
  get 'logout' => 'sessions#destroy', :as => :logout
  get 'insights' => 'home#admin_insights', :as => :admin_insights
  get 'actions' => 'home#admin_actions', :as => :admin_actions
  get 'welcome' => 'home#customer_home', :as => :customer_home
  get 'baker_home' => 'home#baker_home', :as => :baker_home
  get 'shipper_home' => 'home#shipper_home', :as => :shipper_home


  get 'registered' => 'sessions#create', :as => :create_session

  get 'add_to_cart' => 'orders#add_to_cart', :as => :add_to_cart
  get 'remove_from_cart' => 'orders#remove_from_cart', :as => :remove_from_cart
  get 'clear_cart' => 'orders#clear_cart', :as => :clear_cart

  get 'toggle_shipped' => 'order_items#toggle_shipped', :as => :toggle_shipped

  get 'toggle_item_state' => 'items#toggle_item_state', :as => :toggle_item_state
  get 'toggle_customer_state' => 'customers#toggle_customer_state', :as => :toggle_customer_state
  get 'toggle_address_state' => 'addresses#toggle_address_state', :as => :toggle_address_state
  
  # Set the root url
  root :to => 'home#home'

  # Searching
  get 'home/search', to: 'home#search', as: :search
  
end

app/views/partials/_add_new_object.html.erb
<!-- Add a button for new instances of object -->
  <%= link_to(eval("new_#{model_name}_path"), class: "waves-effect waves-light btn") do %>
    <strong>Add a New <%= model_name.capitalize %></strong>
  <% end %>

app/views/partials/_address_info.html.erb
<%= address.street_1 %><br />
<% unless address.street_2.blank? %>
  <%= address.street_2 %><br />
<% end %>
<%= address.city %>, <%= address.state %> <%= address.zip %>

app/views/partials/_display_base_errors.html.erb
<% unless object.errors.empty? %>
  <div data-alert data-options="animation_speed:500, animation:'fadeOut';" class="alert-box warning">
    <%= object.errors[:base].first %>
  </div>
<% end %>

app/views/partials/_flash.html.erb
<% flash.each do |name, msg| %>
  <div data-alert data-options="animation_speed:500, animation:'fadeOut';" class="alert-box <%= flash[:notice] ? "success" : "warning" %>">
    <!-- <a href="#" class="close">&times;</a> -->
    <%= msg %>
  </div>
<% end %>

app/views/partials/_footer.html.erb
<p class="supertiny">&nbsp;</p>

<div id="footer" class="center-align">
  
  <%= link_to 'Home', home_path %>&nbsp;&nbsp;&nbsp;&nbsp;
  <%= link_to 'About Baking Factory', about_path %>&nbsp;&nbsp;&nbsp;&nbsp;
  <%= link_to 'Contact Us', contact_path %>&nbsp;&nbsp;&nbsp;&nbsp;
  <%= link_to 'Privacy Policy', privacy_path %>
  <br />
  <div id="copy">
    Webmaster:&nbsp;&nbsp;<%= mail_to("cmay1@andrew.cmu.edu", "CJ May", encode: "javascript") %> 
    &nbsp;&nbsp;&copy 2019
  </div>

</div>

app/views/partials/_form2_structure.html.erb
<div class="row">
  <div class="col s9">
    <div class="card">    
      <div class="card-content">
        <span class="card-title"><%= type_of_form %></span>
        <%= simple_form_for(object) do |f| %>
          <%= f.error_notification %>
          <div class="row">
            <div class="form-inputs">
              <%= render partial: "#{fields1}", locals: { f: f } %>
            </div>
          </div>
      </div>
    </div>

    <div class="row">
      <div class="col s12">
        <div class="card">
          <div class="row">
            <div class="card-content">
              <span class="card-title"><%= section_2 %></span>
              <div class="form-inputs">
                <%= f.simple_fields_for :user do |ff|%>
                    <%= render partial: "#{fields2}", locals: { ff: ff} %>
                <% end %>
              </div>
            </div>
          </div>    
        </div>              
      </div>
    </div>

      <div class="row">
        <div class="form-actions col s9">
          <%= f.button :submit, "REGISTER" %>
        </div>
      </div>
    <% end %>
  </div>
</div>


<div class="row">
  <div class="col s6">
    <%= link_to :back do %>
      <i class="material-icons">arrow_back</i>
      <p>Back</p>
    <% end %>
  </div>
</div>

app/views/partials/_form_structure.html.erb
<div class="row">
  <div class="col s9">
    <div class="card">    
      <div class="card-content">
        <span class="card-title"><%= type_of_form %></span>
        <%= simple_form_for(object) do |f| %>
          <%= f.error_notification %>
          <div class="row">
            <div class="form-inputs">
              <%= render partial: "#{fields}", locals: { f: f } %>
          </div>
        </div>
      </div>
    </div>
      <div class="row">
        <div class="form-actions col s9">
          <%= f.button :submit %>
          <% if current_user.role?(:admin) && defined?(object.active) %>
            <%= link_to "Make #{object.active ? "Inactive" : "Active"}", eval("toggle_#{object.class.name.downcase}_state_path(#{object.class.name.downcase}_id: #{object.id})"), class: "waves-effect waves-light btn" %>
          <% end %>
        </div>
      </div>
    <% end %>
  </div>
</div>
<%= link_to('Back', :back) %>

app/views/partials/_index_structure.html.erb
<div class="row">
  <div class="col s12">
    <!-- primary partial gets displayed here in main div -->
    <%= render partial: "#{primary}" %>
    <!-- sometimes we want another partial below -->
    <% unless secondary.nil? %>
      <p>&nbsp;</p>
      <%= render partial: "#{secondary}" %>
    <% end %>
    
  </div>
  <div class="col s4">
    <!-- render the sidebar, if it exists -->
    <%= render partial: "#{sidebar}" unless sidebar.blank? %>
  </div>
</div>

<!-- Add a button for new instances of object -->
<% if !defined?(no_add) %>
  <%= link_to(eval("new_#{model_name}_path"), class: "waves-effect waves-light btn") do %>
    <!-- <i class="fa fa-plus"></i> -->
    &nbsp;Add a New <%= model_name.capitalize %>
  <% end %>
<% end %>

app/views/partials/_item_list.html.erb
<% unless items.nil? || items.empty? %>
  <h5><%= item_type.capitalize %></h5>
  <table class="table table-striped">
    <thead>
      <tr>
        <th width="300">Name</th>
        <th width="100">Price</th>
        <th width="100">Units</th>
        <% if controller.controller_name == 'orders' %>
          <th width="100">&nbsp;</th>
        <% end %>
      </tr>
    </thead>
    <tbody>
      <% items.each do |item| %>
        <tr>
          <td><%= link_to item.name, item_path(item) %></td>
          <td><%= number_to_currency item.current_price %></td>
          <td><%= item.units_per_item %> <%= item_type == 'bread' ? 'loaf' : item_type %></td>
          <% if controller.controller_name == 'orders' %>
            <td>
              <%= link_to(add_to_cart_path(item.id), class: 'button tiny radius') do %>
                &nbsp;Add to Cart&nbsp;
              <% end %>
            </td>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
<% end %>

app/views/partials/_object_options.html.erb
<% opt = "#{object.respond_to?(:name) ? object.name : model_name.capitalize }" %>

<div class="form-actions">
  <div class="row">
  <% if can? :edit, object %>
    <% if defined?(object.active) %>
      <%= link_to(eval("toggle_#{object.class.name.downcase}_state_path(#{object.class.name.downcase}_id: #{object.id})"), class: "waves-effect waves-light btn") do %>
      &nbsp;<%= "Make #{object.active ? "Inactive" : "Active"}"%>
      <% end %>
    <% end %>
    &nbsp;&nbsp;
    <%= link_to(eval("edit_#{model_name}_path(object)"), class: 'waves-effect waves-light btn') do %>
        &nbsp;<%= "Edit #{opt}" %>
    <% end %>
    &nbsp;&nbsp;
  <% end %>
  <% if can?(:add_to_cart, Order) && controller.controller_name == 'items' && current_user.role?(:customer)%>
    <%= link_to 'Add To Cart', add_to_cart_path(item_id: object.id), class:"btn waves-effect waves-light" %>
  <% end %>

  <% if can?(:destroy, object) && controller.respond_to?(:destroy) %>
    <%= link_to(eval("#{model_name}_path(object)"), method: 'delete', data: {confirm: "Are you sure you want to permanently delete #{opt}"}, class: 'waves-effect waves-light btn btn-alert') do %>
        &nbsp;<%= "Delete #{opt}" %>
    <% end %>
  <% end %>
  </div>
  <div class="row">
    <% if can? :index, eval(model_name.capitalize) %>
      <%= link_to(eval("#{model_name.pluralize}_path"), class: 'waves-effect waves-light btn green') do %>
        &nbsp;Display All <%# model_name.pluralize.capitalize %>
      <% end %>
      &nbsp;&nbsp;
    <% end %>
  </div>


</div>

app/views/partials/_order_item_list.html.erb
<table class="table table-striped">
  <thead>
    <tr>
      <th width="100">Quantity</th>
      <th width="300">Item</th>
      <th width="100">Unit Price</th>
      <th width="100">Subtotal</th>
      <% if controller.controller_name == 'home' %>
        <th>&nbsp;</th>
      <% end %>
    </tr>
  </thead>
  <tbody>
    <% order_items.each do |oi| %>
      <tr>
        <td align="center"><%= oi.quantity %></td>
        <td><%= link_to oi.item.name, item_path(oi.item) %></td>
        <td align="center"><%= number_to_currency oi.item.price_on_date(date) %></td>
        <td align="right"><%= number_to_currency oi.subtotal(date) %>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td>
        <% if controller.controller_name == 'home' %>
          <td>
            <% if oi.shipped_on.nil? %>
              <%= link_to(image_tag('check_black.gif'), mark_shipped_path(oi.id), method: 'patch') %>
            <% else %>
              <%= link_to(image_tag('check_green.gif'), mark_unshipped_path(oi.id), method: 'patch') %>
            <% end %>
          </td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/partials/_previous_orders.html.erb
<% unless @previous_orders.empty? %>
  <div class="card">
    <div class="card-content">
      <span class="card-title">Other Orders</span>
      <table>
      <thead>
        <tr>
          <th width="50">Date</th>
          <th width="50">Amount</th>
        </tr>
      </thead>
      <tbody>
      <% (@previous_orders - [@order]).each do |order| %>
        <tr>
          <td><%= link_to order.date.strftime('%m/%d/%y'), order_path(order) %></td>
          <td><%= number_to_currency order.grand_total %></td>
        </tr>
      <% end %>
    </table>
    </div>
  </div>
<% end %>

app/views/partials/_structure1.html.erb
<div class="row">
  <div class="col s8">
    <!-- primary partial gets displayed here in main div -->
    <%= render partial: "#{primary}" %>
    <!-- sometimes we want another partial below -->
    <% unless secondary.nil? %>
      <p>&nbsp;</p>
      <%= render partial: "#{secondary}" %>
    <% end %>
  </div>
  <div class="col s4">
    <!-- render the sidebar, if it exists -->
    <%= render partial: "#{sidebar}" unless sidebar.blank? %>
  </div>
</div>

<div class="row">
  <%= render :partial => "partials/display_base_errors", locals: {object: object} %>
</div>

app/views/partials/_topbar.html.erb
<div class="" id="topbar">
  <div class="">
    <%= link_to(image_tag('logos/baker.svg', id: 'topbar_image'), home_path) %>
  </div>
  <div class="">
    <% if current_user.nil? %>
      <h2><%= link_to "Baking Factory", home_path, class: "home_link" %></h2>
    <% elsif current_user.role == 'admin' %>
      <h2><%= link_to "Baking Factory", admin_insights_path, class: "home_link" %></h2>
    <% elsif current_user.role == 'customer' %>
      <h2><%= link_to "Baking Factory", customer_home_path, class: "home_link" %></h2>
    <% elsif current_user.role == 'baker' %>
      <h2><%= link_to "Baking Factory", baker_home_path, class: "home_link" %></h2>
    <% elsif current_user.role == 'shipper' %>
      <h2><%= link_to "Baking Factory", shipper_home_path, class: "home_link" %></h2>
    <% else %>
      <h2><%= link_to "Baking Factory", home_path, class: "home_link" %></h2>
    <% end %>
  </div>
  <div id="reg-btns">
    <% if logged_in? %>
      <p> Welcome, <%= current_user.username%>&nbsp;:&nbsp;<%= current_user.role%></p>
    <% else %>
      <p> </p>
    <% end %>
  </div>
  <div>
    <% if logged_in? %>
      <div class="">
        <%= link_to "LOGOUT", logout_path, class: "waves-effect waves-light btn hide-on-small-and-down", id: "loginout" %>
      </div>
    <% else %>
      <div class="">
        <%= link_to "LOGIN", login_path, class: "waves-effect waves-light btn hide-on-small-and-down", id: "loginout" %>
        <%= link_to "REGISTER", new_customer_path, class: "waves-effect waves-light btn btn-alert hide-on-small-and-down", id: "loginout"%>
      </div>
    <% end %>
  </div>

</div>