config/routes.rb
Rails.application.routes.draw do
  
  # Routes for main resources
  resources :addresses
  resources :customers
  resources :orders
  resources :users
  resources :sessions
  resources :items
  resources :item_prices

  # Semi-static page routes
  get 'home' => 'home#home', as: :home
  get 'about' => 'home#about', as: :about
  get 'contact' => 'home#contact', as: :contact
  get 'privacy' => 'home#privacy', as: :privacy
  get 'login' => 'sessions#new', :as => :login
  get 'logout' => 'sessions#destroy', :as => :logout
  get 'insights' => 'home#admin_insights', :as => :admin_insights
  get 'actions' => 'home#admin_actions', :as => :admin_actions
  get 'welcome' => 'home#customer_home', :as => :customer_home
  get 'baker_home' => 'home#baker_home', :as => :baker_home
  get 'shipper_home' => 'home#shipper_home', :as => :shipper_home


  get 'registered' => 'sessions#create', :as => :create_session

  get 'add_to_cart' => 'orders#add_to_cart', :as => :add_to_cart
  get 'remove_from_cart' => 'orders#remove_from_cart', :as => :remove_from_cart
  get 'clear_cart' => 'orders#clear_cart', :as => :clear_cart

  get 'toggle_shipped' => 'order_items#toggle_shipped', :as => :toggle_shipped

  get 'toggle_item_state' => 'items#toggle_item_state', :as => :toggle_item_state
  get 'toggle_customer_state' => 'customers#toggle_customer_state', :as => :toggle_customer_state
  get 'toggle_address_state' => 'addresses#toggle_address_state', :as => :toggle_address_state
  
  # Set the root url
  root :to => 'home#home'

  # Searching
  get 'home/search', to: 'home#search', as: :search
  
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :check_login, only: [:insights, :actions, :baker_home, :shipper_home]
  authorize_resource :class => false, only: [:insights, :actions, :baker_home, :shipper_home]

  def home
  end

  def about
  end

  def privacy
  end

  def contact
  end

  def insights
  end

  def actions
  end

  def customer_home
    @recent_orders = current_user.customer.orders.chronological.limit(3)
    @suggested_item = Item.order(1).first
    @suggested_again = Item.order(2).first
  end

  def baker_home
    @breads = create_baking_list_for('bread')
    @muffins = create_baking_list_for('muffins')
    @pastries = create_baking_list_for('pastries')
  end

  def shipper_home
    @orders = Order.not_shipped
  end

  def search
    redirect_back(fallback_location: home_path) if params[:query].blank?
    @query = params[:query]
    # Basic search
    @items = Item.search(@query)
    if logged_in? && current_user.role?(:admin)
      @customers = Customer.search(@query)
      @total_hits = @customers.size + @items.size
    else
      @total_hits = @items.size
    end

    # Multisearch
    # @results = PgSearch.multisearch(@query)
    # @total_hits = @results.size

    # Better search
    # @customers = Customer.search_name(@query) + Customer.search(@query)
    # @items = Item.search_name(@query)
    # @total_hits = @customers.size + @items.size

  end

  def create_baking_list_for(category)
    # returns a hash of item name and quantity to be baked for a 
    # particular category of items like bread, muffins, etc.
    #byebug
    all_items = Item.for_category(category).map(&:name).sort
    puts(all_items)
    baking_list = Hash[all_items.map{|name| [name, 0]}]
    puts(baking_list)
    unshipped_items = OrderItem.unshipped.map{|oi| [oi.item.name, oi.quantity] if all_items.include?(oi.item.name)}.compact
    puts(unshipped_items)
    unshipped_items.each{|name, quant| baking_list[name] += quant} unless unshipped_items.nil?
    puts(baking_list)
    baking_list.delete_if{|key, value| value == 0}
    puts(baking_list)
    return baking_list
  end
  helper_method :create_baking_list_for




end

app/views/home/_admin_overview.html.erb
<script src="https://code.highcharts.com/highcharts.js"></script>
<script src="https://code.highcharts.com/modules/series-label.js"></script>
<script src="https://code.highcharts.com/modules/exporting.js"></script>
<script src="https://code.highcharts.com/modules/export-data.js"></script>

<div id="overview-chart"></div>



<div id="time1"></div>


<div id="time2"></div>

app/views/home/_admin_top_customers.html.erb
<script src="https://code.highcharts.com/highcharts.js"></script>
<script src="https://code.highcharts.com/modules/exporting.js"></script>
<script src="https://code.highcharts.com/modules/export-data.js"></script>

<div id="top-customers" style="min-width: 310px; height: 400px; margin: 0 auto"></div>

app/views/home/_baking_list.html.erb
<% if items.empty? %>
    <h5>There are no <%= category %> items to bake at this time.</h5>
<% else %>
    <table class="table striped">
    <thead>
        <tr>
        <th width="70">Item</th>
        <th width="50">Quantity</th>
        </tr>
    </thead>
    <tbody>
        <% items.each do |name, quantity| %>
        <tr>
            <td><%= name %></td>
            <td><%= quantity %></td>
        </tr>
        <% end %>
    </tbody>
    </table>
<% end %>

app/views/home/_general_home.html.erb
<h3>Welcome to the Baking Factory</h3>
<br />
<div class="row">
	<div class="small-7 columns">
		<p>
			Bread Express is the smallest, but absolutely best, online bakery 
			we know of.  You should order lots of our products now.  They are
			delicious, nutritious and amazing in every way.  Why are you still 
			reading this?  You should be ordering bread right now.  Stop reading 
			and start ordering.  (Still reading? What are you waiting for?)
		</p>
	</div>
	<div class="small-1 columns">
		&nbsp;
	</div>
	<div class="small-4 columns">
		&nbsp;
	</div>
</div>

app/views/home/_shipping_list.html.erb
<% orders.each do |order| %>
  <ul class="collapsible popout" data-collapsible="accordion">
    <li>
        <% if order == orders.first %>
            <div class="collapsible-header active"><i class="material-icons">credit_card</i>
        <% else %>
            <div class="collapsible-header"><i class="material-icons">credit_card</i>
        <% end%>
            <div>Order For: <%= order.customer.proper_name %> </div>
            <div class="searchy"></div>
            <div>Placed On: <%= order.created_at.strftime('%B %e, %Y at %l:%M%P') %></div>
        </div>
        <div class="collapsible-body">
            <div class="row">
                <h5>Shipping Address: </h5>
                <%= render :partial => "partials/address_info", locals: {address: order.address} %>
            </div>
            <table class="table">
                <thead>
                    <tr>
                        <th width="70">Item</th>
                        <th width="50">Quantity</th>
                        <th width="30">Shipped?</th>
                    </tr>
                </thead>
                <tbody>
                    <% order.order_items.each do |oitem| %>
                        <tr>
                            <td><%= oitem.item.name %></td>
                            <td><%= oitem.quantity %></td>
                            <td>
                            <% if order.unshipped_items.size == 1 && oitem.shipped_on.nil? %>
                                <%= link_to "#{oitem.shipped_on.nil? ? "Ready to Ship" : "Undo Shipment"}", toggle_shipped_path(order_item_id: oitem.id), class: "waves-effect waves-light btn #{oitem.shipped_on.nil? ? "green" : "red"}", data: {confirm: "Are you sure you want to finalize the shipment for this order?"} %>
                            <% else %>
                                <%= link_to "#{oitem.shipped_on.nil? ? "Ready to Ship" : "Undo Shipment"}", toggle_shipped_path(order_item_id: oitem.id), class: "waves-effect waves-light btn #{oitem.shipped_on.nil? ? "green" : "red"}" %>
                            <% end %>
                            </td>
                        </tr>
                    <% end %>
                </tbody>
            </table>
        </div>
    </li>
  </ul>
<% end %>

app/views/home/about.html.erb
<div class="row">
  <div class="small-7 columns">
    <h2><em>About The Baking Factory</em></h2>

    <p>
    	Some witty language needs to go here...
    </p>
    <p>&nbsp;</p>
    <p>&nbsp;</p>
    <p>&nbsp;</p>
    <p>&nbsp;</p>

    <div>Icons made by <a href="https://www.freepik.com/" title="Freepik">Freepik</a> from <a href="https://www.flaticon.com/" 			    title="Flaticon">www.flaticon.com</a> is licensed by <a href="http://creativecommons.org/licenses/by/3.0/" 			    title="Creative Commons BY 3.0" target="_blank">CC 3.0 BY</a></div>
  </div>
</div>

app/views/home/admin_actions.html.erb
<h4>Quick Actions</h4>

<div class="bar z-depth-1 ">
    <div class="quick">
    &nbsp;&nbsp;&nbsp;&nbsp;
    </div>
    <div class="searchy card">
        <%= form_with url: search_path, method: :get, class: "form-inline searchy", id: "search" do %>
            <%= text_field_tag 'query', '', placeholder: "Find a customer or an item..." %>
        <% end %>
        <i class="material-icons right">search</i>
    </div>
    <div class="quick">
    &nbsp;&nbsp;&nbsp;&nbsp;
    </div>
</div>

<div class="bar z-depth-1 ">
    <div class="quick">
        <%= link_to "New Customer", new_customer_path, class: "waves-effect waves-light btn" %>
    </div>
    <div>
        <%= link_to "Display All", customers_path, class: "waves-effect waves-light btn green" %>
    </div>
</div>

<div class="bar z-depth-1 ">
    <div class="quick">
        <%= link_to "New Item", new_item_path, class: "waves-effect waves-light btn" %>
    </div>
    <div>
        <%= link_to "Display All", items_path, class: "waves-effect waves-light btn green" %>
    </div>
</div>

<div class="bar z-depth-1 ">
    <div class="quick">
        <%= link_to "New Address", new_address_path, class: "waves-effect waves-light btn" %>
    </div>
    <div>
        <%= link_to "Display All", addresses_path, class: "waves-effect waves-light btn green" %>
    </div>
</div>

<div class="bar z-depth-1 ">
    <div class="quick">
        <%= link_to "New Order", new_order_path, class: "waves-effect waves-light btn" %>
    </div>
    <div>
        <%= link_to "Baking Status", baker_home_path, class: "waves-effect waves-light btn green" %>
    </div>
    <div>
        <%= link_to "Shipping Status", shipper_home_path, class: "waves-effect waves-light btn green" %>
    </div>
</div>

app/views/home/admin_insights.html.erb
<%= render :partial => "partials/title_with_search", locals: {title: "Baking Factory Insights"} %>
<div id="tabbed">
  <tabs>

    <tab name="overview" v-bind:selected="true">
        <%= render :partial => "admin_overview" %>
    </tab>

    <tab name="top customers">
        <%= render :partial => "admin_top_customers" %>
    </tab>

    <tab name="popular items">
        <%= render :partial => "admin_popular_items" %>
    </tab>

  </tabs>
</div>

app/views/home/baker_home.html.erb
<h4>Baking List</h4>
<div id="tabbed">
    <tabs>
        <tab name="Bread" v-bind:selected="true">
            <%= render partial: "baking_list", locals: {items: @breads, category: 'bread'} %>
        </tab>

        <tab name="Muffins">
            <%= render partial: "baking_list", locals: {items: @muffins, category: 'muffin'} %>
        </tab>

        <tab name="Pastries">
            <%= render partial: "baking_list", locals: {items: @pastries, category: 'pastry'} %>
        </tab>

    </tabs>

</div>

app/views/home/customer_home.html.erb
<div class="container">
<%= render :partial => "partials/title_with_search", locals: {title: "Hi, #{current_user.customer.first_name}"} %>

  <div class="slider">
    <ul class="slides">
      <li>
        <%= image_tag("apple_cake.jpg") %> <!-- random image -->
        <div class="caption center-align">
          <h3>Apple Cherry Bread</h3>
          <h5 class="light grey-text text-lighten-3">Featured Item</h5>
        </div>
      </li>
      <li>
        <%= image_tag("croissant.jpg") %> <!-- random image -->
        <div class="caption left-align">
          <h3>Check Out Our New Delicious Treat!</h3>
          <h5 class="light grey-text text-lighten-3">Crossiants</h5>
        </div>
      </li>
      <li>
        <%= image_tag("carrot_cupcake.jpg") %> <!-- random image -->
        <div class="caption right-align">
          <h3>Happy Summer!</h3>
          <h5 class="light grey-text text-lighten-3">Try our most popular summer treat</h5>
        </div>
      </li>
      <li>
        <%= image_tag("smiling.jpg") %> <!-- random image -->
        <div class="caption center-align">
          <h3>Contact us!</h3>
          <h5 class="light grey-text text-lighten-3">We'd love to hear from you!</h5>
        </div>
      </li>
    </ul>
  </div>
  <div class="row">
  </div>
  <div class="row">
    <div class="col s12 cards-container">
       <div class="card blue-grey darken-1 hoverable">
        <div class="card-image">
            <%= link_to(image_tag(@suggested_item.picture_url.nil? ? 'no_image_found.png' : @suggested_item.picture_url, class: 'edit-item-picture'), item_path(@suggested_item)) %></td>
        </div>
         <div class="card-content white-text">
           <span class="card-title"><%=@suggested_item.name%></span>
           <p><%= @suggested_item.description %></p>
         </div>
         <div class="card-action">
           <%= link_to 'More Info', item_path(@suggested_item) %>
           <%= link_to 'Add To Cart', add_to_cart_path(item_id: @suggested_item.id) %>
         </div>
        </div>
       <div class="card blue-grey darken-1 hoverable">
         <div class="card-content white-text">
           <span class="card-title">Card Title</span>
           <p>I am a very simple card. I am good at containing small bits of information.</p>
         </div>
         <div class="card-action">
           <a href="#">This is a link</a>
           <a href="#">This is a link</a>
         </div>
        </div>
       <div class="card blue-grey darken-1 hoverable">
         <div class="card-content white-text">
           <span class="card-title">Recent Orders</span>
            <table class="table">
                <thead>
                    <tr>
                        <th></th>
                        <th></th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>
                    <% @recent_orders.each do |order| %>
                        <tr>
                            <td><%= link_to(image_tag(order.order_items.first.item.picture_url.nil? ? 'no_image_found.png' : order.order_items.first.item.picture_url, id: 'topbar_image'), order_path(order)) %></td>
                            <td>Items: <%= order.order_items.size %> </td>
                            <td><%= link_to 'Reorder', add_to_cart_path(order_items: order.order_items.map(&:id)), class: "btn waves-effect waves-light green" %> </td>
                        </tr>
                    <% end %>
                </tbody>
            </table>
         </div>
         <div class="card-action">
           <%= link_to 'Other Orders', orders_path %>
           <%= link_to 'Checkout', new_order_path %>
         </div>
        </div>
       <div class="card blue-grey darken-1 hoverable">
         <div class="card-content white-text">
           <span class="card-title">Card Title</span>
           <p>I am a very simple card. I am good at containing small bits of information.
             I am convenient because I require little markup to use effectively.</p>
         </div>
         <div class="card-action">
           <a href="#">This is a link</a>
           <a href="#">This is a link</a>
         </div>
        </div>
       <div class="card blue-grey darken-1 hoverable">
         <div class="card-content white-text">
           <span class="card-title">Your Account</span>
           <p>Welcome back, <%= current_user.customer.first_name%>! Use the links below to edit the information in your account. Please use the contact us link below if you have any issues or questions.</p>
         </div>
         <div class="card-action">
           <%= link_to 'Addresses', addresses_path %>
           <%= link_to 'Edit Profile', edit_customer_path(current_user.customer) %>
         </div>
        </div>
       <div class="card blue-grey darken-1 hoverable">
         <div class="card-image">
            <%= link_to(image_tag(@suggested_again.picture_url.nil? ? 'no_image_found.png' : @suggested_again.picture_url, class: 'edit-item-picture'), item_path(@suggested_again)) %></td>
        </div>
         <div class="card-content white-text">
           <span class="card-title"><%=@suggested_again.name%></span>
           <p><%= @suggested_again.description %></p>
         </div>
         <div class="card-action">
           <%= link_to 'More Info', item_path(@suggested_again) %>
           <%= link_to 'Add To Cart', add_to_cart_path(item_id: @suggested_again.id) %>
         </div>
        </div>
    </div>
  </div>
</div>

app/views/home/home.html.erb
	<%= render :partial => 'general_home' %>

app/views/home/privacy.html.erb
<div class="row">
	<div class="small-7 columns">
		<h2>A &amp; M Bread Express Privacy Policy</h2>

		<p>The Bread Express privacy policy is very simple, rarely changes, and 
			does not require a lawyer to understand it.  
			We will pounce on the opportunity to sell every bit of information 
			on you they have at our disposal.  We will gladly sell your address, 
			phone, email, age, name of pet, name of favorite superhero, color of 
			bunny slippers you wear at home, and the like, to any willing buyer 
			who will pay the big bucks.  (BTW, we <em>know</em> you wear bunny 
			slippers at home and we know what color they are.  You really have 
			no secrets from this crew.)  If you have sensitive information that 
			you don't want us to share with the world, then keep it to yourself 
			-- don't tell us.  
			<br><br>
			It's really that simple.
		</p>

		<p>&nbsp;</p>
		<p>&nbsp;</p>
		<p>&nbsp;</p>
	</div>
</div>

app/views/home/search.html.erb
<h5>Search result for term <em>'<%= @query %>'</em> resulted in <%= pluralize(@total_hits, 'hit') %></h5>
<p class="supertiny">&nbsp;</p>

<% if logged_in? && current_user.role?(:admin) %>
  <% unless @customers.empty? %>
    <p><em><strong>Customers matching term '<%= @query %>'</strong></em></p>
    <ul>
      <% for customer in @customers do %>
        <li><%= link_to customer.proper_name, customer_path(customer) %></li>
      <% end %>
    </ul>
    <p class="smtext">&nbsp;</p>
  <% end %>
<% end %>

<% unless @items.empty? %>
  <p><em><strong>Items matching term '<%= @query %>'</strong></em></p>
  <ul>
    <% for item in @items do %>
      <li><%= link_to item.name, item_path(item) %></li>
    <% end %>
  </ul>
  <p class="supertiny">&nbsp;</p>
<% end %>


<%= link_to 'Back', :back %>

app/views/home/shipper_home.html.erb
<h4>Orders to Ship:</h4>
<% if @orders.empty?%>
    <h5><em>There are currently no orders to ship.</em></h5>
<% else %>
    <%= render partial: "shipping_list", locals: {orders: @orders} %>
<% end %>