config/routes.rb
Rails.application.routes.draw do
  
  # Routes for main resources
  resources :addresses
  resources :customers
  resources :orders
  resources :users
  resources :sessions
  resources :items
  resources :item_prices

  # Semi-static page routes
  get 'home' => 'home#home', as: :home
  get 'about' => 'home#about', as: :about
  get 'contact' => 'home#contact', as: :contact
  get 'privacy' => 'home#privacy', as: :privacy
  get 'login' => 'sessions#new', :as => :login
  get 'logout' => 'sessions#destroy', :as => :logout
  get 'insights' => 'home#admin_insights', :as => :admin_insights
  get 'actions' => 'home#admin_actions', :as => :admin_actions
  get 'welcome' => 'home#customer_home', :as => :customer_home
  get 'baker_home' => 'home#baker_home', :as => :baker_home
  get 'shipper_home' => 'home#shipper_home', :as => :shipper_home


  get 'registered' => 'sessions#create', :as => :create_session

  get 'add_to_cart' => 'orders#add_to_cart', :as => :add_to_cart
  get 'remove_from_cart' => 'orders#remove_from_cart', :as => :remove_from_cart
  get 'clear_cart' => 'orders#clear_cart', :as => :clear_cart

  get 'toggle_shipped' => 'order_items#toggle_shipped', :as => :toggle_shipped

  get 'toggle_item_state' => 'items#toggle_item_state', :as => :toggle_item_state
  get 'toggle_customer_state' => 'customers#toggle_customer_state', :as => :toggle_customer_state
  get 'toggle_address_state' => 'addresses#toggle_address_state', :as => :toggle_address_state
  
  # Set the root url
  root :to => 'home#home'

  # Searching
  get 'home/search', to: 'home#search', as: :search
  
end

app/models/order.rb
class Order < ApplicationRecord
  # get module to help with some functionality
  include AppHelpers::Validations
  include AppHelpers::Deletions
  include AppHelpers::Shipping
  require 'base64'

  # Relationships
  belongs_to :customer
  belongs_to :address
  has_many :order_items
  has_many :items, through: :order_items

  # Virtual attributes (non-saved)
  attr_accessor :credit_card_number
  attr_accessor :expiration_year
  attr_accessor :expiration_month

  # Scopes
  scope :chronological, -> { order(date: :desc) }
  scope :paid,          -> { where.not(payment_receipt: nil) }
  scope :for_customer,  ->(customer_id) { where(customer_id: customer_id) }

  # Class methods
  def self.not_shipped
    # joins(:order_items).where("order_items.shipped_on IS NULL").to_a.uniq
    joins(:order_items).where("order_items.shipped_on IS NULL").distinct

  end

  # Other methods
  def unshipped_items
    self.order_items.unshipped
  end

  # Validations
  # validates_date :date
  # validates_numericality_of :grand_total, greater_than_or_equal_to: 0, allow_blank: true
  validates_presence_of :customer_id, :address_id
  validate :customer_is_active_in_system
  validate :address_is_active_in_system
  validate :credit_card_number_is_valid
  validate :expiration_date_is_valid

  # Other methods
  def is_editable?
    !self.order_items.unshipped.empty?
  end

  def pay
    return false unless self.payment_receipt.nil?
    generate_payment_receipt
    self.save!
    self.payment_receipt
  end

  def total_weight
    weight = self.order_items.inject(0){|sum, oi| sum += oi.item.weight * oi.quantity}
  end

  def shipping_costs
    calculate_shipping_costs(self.total_weight, base=2.00)
  end

  def credit_card_type
    credit_card.type.nil? ? "N/A" : credit_card.type.name
  end

  # Callbacks
  before_destroy do
    check_if_any_order_items_shipped
    if errors.present?
      @destroyable = false
      throw(:abort)
    end
    remove_order_items
  end

  private
  def customer_is_active_in_system
    is_active_in_system(:customer)
  end

  def address_is_active_in_system
    is_active_in_system(:address)
  end

  def generate_payment_receipt
    self.payment_receipt = Base64.encode64("order: #{self.id}; amount_paid: #{self.grand_total}; received: #{self.date}; card: #{self.credit_card_type} ****#{self.credit_card_number[-4..-1]}; billing zip: #{self.customer.billing_address.zip}")
  end

  def credit_card
    CreditCard.new(self.credit_card_number, self.expiration_year, self.expiration_month)
  end

  def credit_card_number_is_valid
    return false if self.expiration_year.nil? || self.expiration_month.nil?
    if self.credit_card_number.nil? || credit_card.type.nil?
      errors.add(:credit_card_number, "is not valid")
      return false
    end
    true
  end

  def expiration_date_is_valid
    return false if self.credit_card_number.nil? 
    if self.expiration_year.nil? || self.expiration_month.nil? || credit_card.expired?
      errors.add(:expiration_year, "is expired")
      return false
    end
    true
  end

  def check_if_any_order_items_shipped
    unless self.order_items.shipped.empty?
      errors.add(:base, "This order has already been partially shipped and therefore cannot be deleted.")
    end
  end

  def remove_order_items
    self.order_items.each{ |oi| oi.destroy }
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  include AppHelpers::Cart
  include AppHelpers::Shipping

  before_action :set_order, only: [:show, :edit, :destroy]
  before_action :check_login
  authorize_resource

  def index
    if current_user.role == 'customer'
      @previous_orders = current_user.customer.orders.chronological.paginate(:page => params[:page]).per_page(10)
    else
      @all_orders = Order.chronological.paginate(:page => params[:page]).per_page(10)
    end
  end

  def show
    @previous_orders = @order.customer.orders.chronological.to_a
  end

  def new
    @order = Order.new
  end

  def edit
  end

  def create
    @order = Order.new(order_params)
    @order.date = Date.current
    @order.grand_total = calculate_cart_items_cost + calculate_cart_shipping
    @order.customer = current_user.customer
    @order.expiration_year = @order.expiration_year.to_i
    @order.expiration_month = @order.expiration_month.to_i
    if @order.save
      save_each_item_in_cart(@order)
      @order.pay
      clear_cart_items
      redirect_to @order, notice: "Thank you for ordering from the Baking Factory."
    else
      render action: 'new'
    end
  end


  def add_to_cart
    unless params[:order_items].nil?
      items = params[:order_items]
      items.each do |item|
        result = find_item_for(item.to_i)
        add_item_to_cart(result)
      end
    else
      add_item_to_cart(params[:item_id])
    end
    redirect_back(fallback_location: items_path, notice: "Item added to cart")
  end

  def remove_from_cart
    remove_item_from_cart(params[:item_id])
    redirect_back(fallback_location: new_order_path, notice: "Item removed from cart.")
  end

  def clear_cart
    clear_cart_items
    redirect_back(fallback_location: customer_home_path, notice: "Cart cleared.")
  end
  

  private

  def find_item_for(order_item_id)
    return OrderItem.find(order_item_id).item.id
  end

  def set_order
    @order = Order.find(params[:id])
  end

  def order_params
    params.require(:order).permit(:address_id, :customer_id, :grand_total, :item_id, :credit_card_number, :expiration_year, :expiration_month, :order_items)
  end

end

app/views/orders/_all_orders.html.erb
<% if @all_orders.empty? %>
  <p><em>There are no orders at this time.</em></p>
<% else %>
  <%= render :partial => "order_list", locals: {status: 'All', orders: @all_orders} %>  
<% end %>
<br />

app/views/orders/_fields.html.erb
<% if current_user.role?(:admin) %>
    <%= f.input :address_id, collection: get_address_options(@order.customer.user), include_blank: true, label_html: {class: "avg"} %>
<% else %>
    <%= f.input :address_id, collection: get_address_options(current_user), include_blank: true, label_html: {class: "avg"} %>
<% end %>

<% if controller.action_name != 'edit' %>
    <%= f.input :credit_card_number, as: :integer, required: true, label_html: {class: "active avg"} %>
    <%= f.input :expiration_month, collection: 01..12, required: true, label_html: {class: "avg"} %>
    <%= f.input :expiration_year, collection: (Date.today.year.to_i)..(Date.today.year+100), required: true, label_html: {class: "avg"} %>
<% end %>

app/views/orders/_form.html.erb
<%= simple_form_for @order, html: { class: 'form-horizontal' } do |f| %>
  <fieldset>
    <legend>Place an Order with the Baking Factory</legend>

    <%= f.input :customer_id, collection: Customer.active.alphabetical, include_blank: true, input_html: {class: "avg"} %>
    <%= f.input :address_id, collection: get_address_options, include_blank: true, input_html: {class: "avg"} %>
    <%= f.input :grand_total, as: :string, input_html: {class: "avg"} %>

    <div class="form-actions">
      <%= f.submit nil, :class => 'button radius' %>
      <%= link_to 'Cancel', orders_path, :class => 'button alert radius' %>
    </div>
  </fieldset>
<% end %>

app/views/orders/_order_details.html.erb
<h3>Order Details</h3>

<p>
  <b>Date</b>: <%= @order.date.strftime('%B %e, %Y') %>
</p>

<p>
  <b>Customer</b>: <%= link_to @order.customer.name, customer_path(@order.customer) %>
</p>

<p>
  <b>Recipient</b>: <%= link_to @order.address.recipient, address_path(@order.address) %>
</p>

<p>
  <b>Total Cost</b>: <%= number_to_currency @order.grand_total %>
</p>

app/views/orders/_order_history.html.erb
<h4>Order History for <strong><%= current_user.customer.proper_name %></b></h4>
<table class="table striped">
  <thead>
    <tr>
      <th width="100">Date</th>
      <th width="200">Recipient</th>
      <th width="100">Cost</th>
      <th width="50"></th>
    </tr>
  </thead>
  <tbody>
    <% @previous_orders.each do |order| %>
      <tr>
        <td><%= link_to order.date.strftime('%m/%d/%y'), order_path(order) %></td>
        <td><%= link_to order.address.recipient, address_path(order.address) %></td>
        <td><%= number_to_currency order.grand_total %></td>
        <td><%= link_to 'Reorder', add_to_cart_path(order_items: order.order_items.map(&:id)), class: "btn waves-effect waves-light green" %> </td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= will_paginate @previous_orders, previous_label: "Previous&nbsp;", next_label: "&nbsp;Next" %>  

app/views/orders/_order_list.html.erb
<h4><%= status %> Orders</h4>
<table class="table striped">
  <thead>
    <tr>
      <th width="100">Date</th>
      <th width="225">Customer</th>
      <th width="225">Recipient</th>
      <th width="100">Total</th>
      <% if current_user.role?(:admin) %>
          <th class="align_center" width="100">Options</th>
      <% end %>
    </tr>
  </thead>
  <tbody>
    <% orders.each do |order| %>
      <tr>
        <td><%= link_to order.date.strftime('%m/%d/%y'), order_path(order) %></td>
        <td><%= link_to order.customer.name, customer_path(order.customer) %></td>
        <td><%= link_to order.address.recipient, address_path(order.address) %></td>
        <td><%= number_to_currency order.grand_total %></td>
        <td class="align_center">
        <% if current_user.role?(:admin) && order.is_editable? %>
          <%= link_to edit_order_path(order) do %>
            <i class="material-icons">edit</i>
          <% end %>
        <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= will_paginate orders, previous_label: "Previous&nbsp;", next_label: "&nbsp;Next" %>  

app/views/orders/edit.html.erb
<%= render partial: "partials/form_structure", locals: {object: @order, 
                                                        type_of_form: "Edit Order",
                                                        fields: "fields"} %>

app/views/orders/index.html.erb
<% if current_user.role == 'admin' %>
    <%= render partial: "partials/index_structure", locals: {model_name: "order", 
                                                         primary: "all_orders", 
                                                         secondary: nil,
                                                         sidebar: nil,
                                                         no_add: "true"} %>
<% else %>
    <%= render partial: "partials/index_structure", locals: {model_name: "order", 
                                                         primary: "order_history", 
                                                         secondary: nil,
                                                         sidebar: nil,
                                                         no_add: "true"} %>
<% end %>

app/views/orders/new.html.erb
<% if cart_size == 0 %>
    <h4>Add some items to your cart to place an order with us!</h4>
<% else %>
    <div class="row">
        <div class="col s7">
            <div class="card">    
                <div class="card-content">
                    <span class="card-title">Place an Order with The Baking Factory</span>
                    <%= simple_form_for(@order) do |f| %>
                    <%= f.error_notification %>
                    <div class="row">
                        <div class="form-inputs">
                            <%= render partial: "fields", locals: { f: f } %>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="form-actions col s9">
                <%= f.button :submit %>
                </div>
            </div>
            <% end %>
        </div>
        <div class="col s5">
            <div class="card">
                <div class="card-content cart-page-items">
                <span class="card-title">Cart</span>
                <table>
                <thead>
                    <tr>
                    <th width="10">Item</th>
                    <th width="10">Quantity</th>
                    <th width="10">Price</th>
                    <th width="10"></th>
                    </tr>
                </thead>
                <tbody>
                <% get_list_of_items_in_cart.each do |oitem| %>
                    <tr>
                    <td><%= link_to oitem.item.name, item_path(oitem.item) %></td>
                    <td><%= oitem.quantity %>
                    <td><%= number_to_currency oitem.item.current_price %></td>
                    <td><%= link_to remove_from_cart_path(item_id: oitem.item_id) do %><i class="material-icons cart-delete">delete</i><% end %>
                    </tr>
                <% end %>
                </table>
                <div class="right">
                    <p>Subtotal: <b><%= number_to_currency calculate_cart_items_cost %></b></p>
                </div>
                </br>
                <div class="right">
                    <p>Estimated Shipping Costs: <b><%= number_to_currency calculate_cart_shipping %></b></p>
                </div>
                </br>
                <div>
                    <h5 class="right">Grand Total: <b><%= number_to_currency (calculate_cart_items_cost + calculate_cart_shipping) %></b></h5>
                </div>
                </div>
            </div>
        </div>
    </div>
<% end %>
<%= link_to 'Back', :back %>

app/views/orders/show.html.erb
<div class="row">
  <div class="col s7">
    <%= render :partial => "order_details" %>
  </div>
  <div class="col s5">
    <%= render partial: "partials/previous_orders", locals: {previous_orders: @previous_orders}  unless @previous_orders.empty?%>
  </div>
</div>

<%= render partial: "partials/object_options", locals: {model_name: "order", object: @order}  %>