config/routes.rb
Rails.application.routes.draw do
  
  # Routes for main resources
  resources :addresses
  resources :customers
  resources :orders
  resources :users
  resources :sessions
  resources :items
  resources :item_prices

  # Semi-static page routes
  get 'home' => 'home#home', as: :home
  get 'about' => 'home#about', as: :about
  get 'contact' => 'home#contact', as: :contact
  get 'privacy' => 'home#privacy', as: :privacy
  get 'login' => 'sessions#new', :as => :login
  get 'logout' => 'sessions#destroy', :as => :logout
  get 'insights' => 'home#admin_insights', :as => :admin_insights
  get 'actions' => 'home#admin_actions', :as => :admin_actions
  get 'welcome' => 'home#customer_home', :as => :customer_home
  get 'baker_home' => 'home#baker_home', :as => :baker_home
  get 'shipper_home' => 'home#shipper_home', :as => :shipper_home


  get 'registered' => 'sessions#create', :as => :create_session

  get 'add_to_cart' => 'orders#add_to_cart', :as => :add_to_cart
  get 'remove_from_cart' => 'orders#remove_from_cart', :as => :remove_from_cart
  get 'clear_cart' => 'orders#clear_cart', :as => :clear_cart

  get 'toggle_shipped' => 'order_items#toggle_shipped', :as => :toggle_shipped

  get 'toggle_item_state' => 'items#toggle_item_state', :as => :toggle_item_state
  get 'toggle_customer_state' => 'customers#toggle_customer_state', :as => :toggle_customer_state
  get 'toggle_address_state' => 'addresses#toggle_address_state', :as => :toggle_address_state
  
  # Set the root url
  root :to => 'home#home'

  # Searching
  get 'home/search', to: 'home#search', as: :search
  
end

app/views/partials/nav/_nav_admin.html.erb
<ul id="dropdown1" class="dropdown-content">
  <li><%= link_to 'Customers', customers_path %></li>
  <li class="divider"></li>
  <li><%= link_to 'Addresses', addresses_path %></li>
  <li class="divider"></li>
  <li><%= link_to 'Orders', orders_path %></li>
  <li class="divider"></li>
  <li><%= link_to 'Items', items_path %></li>
</ul>
<nav id="nav">
    <div class="container">
        <a href="#" data-activates="mobile-demo" class="button-collapse hide-on-med-and-up right"><i class="material-icons">menu</i></a>
        <ul class="hide-on-small-and-down">
            <li><%= link_to 'Insights', admin_insights_path %></li>
            <li data-activates="dropdown1" class="dropdown-button"><%= link_to admin_actions_path do %>Actions
                <i class="material-icons right">arrow_drop_down</i>
            <% end %> </li>
            <li><%= link_to 'Baking', baker_home_path %></li>
            <li><%= link_to 'Shipping', shipper_home_path %></li>

        </ul>
        <ul class="side-nav right" id="mobile-demo">
        <li><%= link_to 'Insights', admin_insights_path %></li>
        <li><%= link_to 'Baking', baker_home_path %></li>
        <li><%= link_to 'Shipping', shipper_home_path %></li>
        <% if logged_in? %>
            <li><%= link_to "LOGOUT", logout_path, class: "waves-effect waves-light btn", id: "loginout" %></li>
        <% else %>
            <li><%= link_to "LOGIN", login_path, class: "waves-effect waves-light btn", id: "loginout" %>
            <%= link_to "REGISTER", new_customer_path, class: "waves-effect waves-light btn red"%></li>
        <% end %>
        </ul>
    </div>
</nav>

app/views/partials/nav/_nav_baker.html.erb
<nav id="nav">
    <div class="container">
        <a href="#" data-activates="mobile-demo" class="button-collapse hide-on-med-and-up right"><i class="material-icons">menu</i></a>
        <ul class="hide-on-small-and-down">
            <li><%= link_to 'Dashboard', baker_home_path %></li>

        </ul>
        <ul class="side-nav right" id="mobile-demo">
        <li><%= link_to 'Dashboard', baker_home_path %></li>
        <% if logged_in? %>
            <li><%= link_to "LOGOUT", logout_path, class: "waves-effect waves-light btn", id: "loginout" %></li>
        <% else %>
            <li><%= link_to "LOGIN", login_path, class: "waves-effect waves-light btn", id: "loginout" %>
            <%= link_to "REGISTER", new_customer_path, class: "waves-effect waves-light btn red"%></li>
        <% end %>
        </ul>
    </div>
</nav>

app/views/partials/nav/_nav_customer.html.erb
<ul id="dropdown1" class="dropdown-content">
  <li><%= link_to 'Edit Addresses', addresses_path %></li>
  <li class="divider"></li>
  <li><%= link_to 'Order History', orders_path %></li>
  <li class="divider"></li>
  <li><%= link_to 'Edit Profile', edit_customer_path(current_user.customer) %></li>
</ul>
<nav id="nav">
    <div class="container">
        <a href="#" data-activates="mobile-demo" class="button-collapse hide-on-med-and-up right"><i class="material-icons">menu</i></a>
        <ul class="hide-on-small-and-down">
            <li><%= link_to 'For You', customer_home_path %></li>
            <li><%= link_to 'Our Products', items_path %></li>
            <li class="right" id="cart"><%= link_to new_order_path do %>
                <i class="material-icons left cart">shopping_cart</i>(<%= cart_size %>)
            <% end %> </li>
            <li class="right my-account"><%= link_to current_user.customer, data: {activates: "dropdown1"}, class: "dropdown-button" do %>My Account
                <i class="material-icons right">arrow_drop_down</i>
            <% end %> </li>
        </ul>
        <ul class="side-nav right" id="mobile-demo">
          <li><%= link_to 'Our Products', items_path %></li>
          <% if logged_in? %>
              <li><%= link_to "LOGOUT", logout_path, class: "waves-effect waves-light btn", id: "loginout" %></li>
          <% else %>
              <li><%= link_to "LOGIN", login_path, class: "waves-effect waves-light btn", id: "loginout" %>
              <%= link_to "REGISTER", new_customer_path, class: "waves-effect waves-light btn red"%></li>
          <% end %>
        </ul>
    </div>
</nav>

  <div class="shopping-cart z-depth-3">
    <div class="shopping-cart-header">
      <i class="material-icons cart-icon">shopping_cart</i>(<%= cart_size %>)
      &nbsp;&nbsp;&nbsp;&nbsp;Clear Cart: <%= link_to clear_cart_path do %><i class="material-icons clear-cart">delete</i><% end %></span>
      <div class="fill-space"> </div>
      <div class="shopping-cart-total">
        <span class="lighter-text">Subtotal:</span>
        <span class="main-color-text"><%= number_to_currency calculate_cart_items_cost%></span>
      </div>
    </div> <!--end shopping-cart-header -->
    
    
    <ul class="shopping-cart-items">
      <% get_list_of_items_in_cart.each do |oitem| %>
        <li class="row">
          <%= link_to(image_tag(oitem.item.picture_url.nil? ? 'no_image_found.png' : oitem.item.picture_url, class: "edit-item-picture"), item_path(oitem.item)) %>
          <span class="item-name"><%= link_to oitem.item.name, item_path(oitem.item) %><%= link_to remove_from_cart_path(item_id: oitem.item.id) do %><i class="inline-block material-icons right hover-cart-delete">delete</i><% end %></span>
          <span class="item-price"><%= number_to_currency oitem.item.current_price %></span>
          <span class="item-quantity">Quantity: <%= oitem.quantity %></span>
          
        </li>
      <% end %>
    </ul>
    <div class="checkout">
        <%= link_to 'Checkout', new_order_path, class:"waves-effect waves-light btn checkout" %>
    </div>
  </div> <!--end shopping-cart -->

app/views/partials/nav/_nav_guest.html.erb
<nav id="nav">
  <div class="container">
    <ul class="left hide-on-small-and-down">
      <li><%= link_to 'About Us', about_path %></li>
      <li><%= link_to 'Contact Us', contact_path %></li>
      <li><%= link_to 'Our Products', items_path %></li>
    </ul>
    <ul class="right">
      <li></li>
    </ul>
  </div>
</nav>

app/views/partials/nav/_nav_shipper.html.erb
<nav id="nav">
    <div class="container">
        <a href="#" data-activates="mobile-demo" class="button-collapse hide-on-med-and-up right"><i class="material-icons">menu</i></a>
        <ul class="hide-on-small-and-down">
            <li><%= link_to 'Dashboard', shipper_home_path %></li>

        </ul>
        <ul class="side-nav right" id="mobile-demo">
        <li><%= link_to 'Dashboard', shipper_home_path %></li>
        <% if logged_in? %>
            <li><%= link_to "LOGOUT", logout_path, class: "waves-effect waves-light btn", id: "loginout" %></li>
        <% else %>
            <li><%= link_to "LOGIN", login_path, class: "waves-effect waves-light btn", id: "loginout" %>
            <%= link_to "REGISTER", new_customer_path, class: "waves-effect waves-light btn red"%></li>
        <% end %>
        </ul>
    </div>
</nav>